apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: tech-challenge
spec:
  selector:
    matchLabels:
      app: order-api
  replicas: 1
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: tech-challenge/order-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: MERCADO_PAGO_URL
            value: "https://api.mercadopago.com"
          - name: MERCADO_PAGO_USER
            value: "268051208"
          - name: MERCADO_PAGO_TOKEN
            value: "TEST-2699929570739973-012315-c34fb1e302973d0e4970dd6b72b360de-268051208"
          - name: MERCADO_PAGO_EMPRESA_ID
            value: "EMP1"
          - name: MERCADO_PAGO_NOTIFICATION
            value: "https://webhook.site/64403458-1ea5-469a-9427-49d1e4b5cc52"
          - name: ORDER_MS_URL
            value: "https://webhook.site/64403458-1ea5-469a-9427-49d1e4b5cc52"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - name: order-ms-api-volume
          mountPath: /var/www/volume
      volumes:
      - name: order-ms-api-volume
        persistentVolumeClaim:
          claimName: order-ms-api-pvc