apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: tech-challenge
  labels:
    app: order-api
spec:
  selector:
    app: order-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8889
      targetPort: 80
      protocol: TCP