apiVersion: v1
kind: Service
metadata:
  namespace: tech-challenge
  name: payment-ms-db-service
  labels:
    app: payment-ms-db
spec:
  type: NodePort
  selector:
    app: payment-ms-db
  ports:
    - name: "payment-ms-db"
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30432