apiVersion: v1
kind: Service
metadata:
  namespace: tech-challenge
  name: order-ms-db-service
  labels:
    app: order-ms-db
spec:
  type: NodePort
  selector:
    app: order-ms-db
  ports:
    - name: "order-ms-db"
      protocol: TCP
      port: 3307
      targetPort: 3307
      nodePort: 30433