apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tech-challenge
  name: order-ms-db
  labels:
    app: order-ms-db
    tier: mysql
spec:
  selector:
    matchLabels:
      app: order-ms-db
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: tech-challenge
      labels:
        app: order-ms-db
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: order-ms-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: PAYMENT_MS_DB
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3307
          name: mysql
        volumeMounts:
        - name: order-ms-db-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: order-ms-db-volume
        persistentVolumeClaim:
          claimName: order-ms-db-pvc