apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tech-challenge
  name: order-ms-db
  labels:
    app: order-ms-db
    tier: mongodb
spec:
  selector:
    matchLabels:
      app: order-ms-db
      tier: mongodb
  template:
    metadata:
      namespace: tech-challenge
      labels:
        app: order-ms-db
        tier: mongodb
    spec:
      containers:
      - image: mongo
        name: order-ms-db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "mongoroot"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "123456"
          - name: MONGO_INITDB_DATABASE
            value: "pedidos"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: order-ms-db-volume
          mountPath: /data/db
      volumes:
      - name: order-ms-db-volume
        persistentVolumeClaim:
          claimName: order-ms-db-pvc