apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-api
  namespace: tech-challenge
spec:
  selector:
    matchLabels:
      app: production-api
  replicas: 1
  template:
    metadata:
      labels:
        app: production-api
    spec:
      containers:
      - name: production-api
        image: tech-challenge/production-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: APP_NAME
            value: "production-ms"
          - name: DATABASE_HOST
            value: "production-ms-db-service"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            value: "admin"
          - name: DATABASE_PASSWORD
            value: "secretpassword"
          - name: KAFKA_BROKER
            value: "kafka-service"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_TOPIC_PEDIDO_NOVO
            value: "pedido-novo"
          - name: KAFKA_TOPIC_PAGAMENTO_APROVADO
            value: "pagamento-aprovado"
          - name: KAFKA_TOPIC_PAGAMENTO_NAO_APROVADO
            value: "pagamento-nao-aprovado"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 30
          timeoutSeconds: 10
        volumeMounts:
        - name: production-ms-api-volume
          mountPath: /var/www/volume
      volumes:
      - name: production-ms-api-volume
        persistentVolumeClaim:
          claimName: production-ms-api-pvc