apiVersion: v1
kind: Service
metadata:
  name: production-api-service
  namespace: tech-challenge
  labels:
    app: production-api
spec:
  selector:
    app: production-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 80
      protocol: TCP