apiVersion: v1
kind: Service
metadata:
  namespace: tech-challenge
  name: production-ms-db-service
  labels:
    app: production-ms-db
spec:
  type: NodePort
  selector:
    app: production-ms-db
  ports:
    - name: "production-ms-db"
      protocol: TCP
      port: 5432
      targetPort: 5432