apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tech-challenge
  name: production-ms-db-pvc
  labels:
    app: production-ms-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi