apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: tech-challenge
  labels:
    app: payment-api
spec:
  selector:
    app: payment-api
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP