apiVersion: v1
kind: Service
metadata:
  namespace: tech-challenge
  name: kafka-service
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092