apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tech-challenge
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:5.5.3
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "http://localhost:9092"
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9093
          name: internal
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data-pvc
  replicas: 1