apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tech-challenge
  name: kafka-data-pvc
  labels:
    app: kafka
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi